-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2022.2 (win64) Build 3671981 Fri Oct 14 05:00:03 MDT 2022
-- Date        : Mon Apr 13 17:27:46 2026
-- Host        : LAPTOP-ML231TQL running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               f:/_xu/_prj/pcie_uart_tx_array/repo/pcie_uart.gen/sources_1/bd/design_1/ip/design_1_bridge_top_v2_0_0/design_1_bridge_top_v2_0_0_stub.vhdl
-- Design      : design_1_bridge_top_v2_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7a200tfbg676-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_bridge_top_v2_0_0 is
  Port ( 
    clk : in STD_LOGIC;
    rst : in STD_LOGIC;
    interupt_req : out STD_LOGIC;
    interupt_ack : in STD_LOGIC;
    LOGIC_VERSION : in STD_LOGIC_VECTOR ( 31 downto 0 );
    LOGIC_SUB_VERSION : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s01_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s01_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s01_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s01_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s01_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s01_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s01_axi_awvalid : in STD_LOGIC;
    s01_axi_awlock : in STD_LOGIC;
    s01_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s01_axi_awready : out STD_LOGIC;
    s01_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s01_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s01_axi_wlast : in STD_LOGIC;
    s01_axi_wvalid : in STD_LOGIC;
    s01_axi_wready : out STD_LOGIC;
    s01_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s01_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s01_axi_bvalid : out STD_LOGIC;
    s01_axi_bready : in STD_LOGIC;
    s01_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s01_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s01_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s01_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s01_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s01_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s01_axi_arvalid : in STD_LOGIC;
    s01_axi_arlock : in STD_LOGIC;
    s01_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s01_axi_arready : out STD_LOGIC;
    s01_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s01_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s01_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s01_axi_rlast : out STD_LOGIC;
    s01_axi_rvalid : out STD_LOGIC;
    s01_axi_rready : in STD_LOGIC;
    s02_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s02_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s02_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s02_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s02_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s02_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s02_axi_awvalid : in STD_LOGIC;
    s02_axi_awlock : in STD_LOGIC;
    s02_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s02_axi_awready : out STD_LOGIC;
    s02_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s02_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s02_axi_wlast : in STD_LOGIC;
    s02_axi_wvalid : in STD_LOGIC;
    s02_axi_wready : out STD_LOGIC;
    s02_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s02_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s02_axi_bvalid : out STD_LOGIC;
    s02_axi_bready : in STD_LOGIC;
    s02_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s02_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s02_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s02_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s02_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s02_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s02_axi_arvalid : in STD_LOGIC;
    s02_axi_arlock : in STD_LOGIC;
    s02_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s02_axi_arready : out STD_LOGIC;
    s02_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s02_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s02_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s02_axi_rlast : out STD_LOGIC;
    s02_axi_rvalid : out STD_LOGIC;
    s02_axi_rready : in STD_LOGIC;
    s03_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s03_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s03_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s03_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s03_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s03_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s03_axi_awvalid : in STD_LOGIC;
    s03_axi_awlock : in STD_LOGIC;
    s03_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s03_axi_awready : out STD_LOGIC;
    s03_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s03_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s03_axi_wlast : in STD_LOGIC;
    s03_axi_wvalid : in STD_LOGIC;
    s03_axi_wready : out STD_LOGIC;
    s03_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s03_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s03_axi_bvalid : out STD_LOGIC;
    s03_axi_bready : in STD_LOGIC;
    s03_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s03_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s03_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s03_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s03_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s03_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s03_axi_arvalid : in STD_LOGIC;
    s03_axi_arlock : in STD_LOGIC;
    s03_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s03_axi_arready : out STD_LOGIC;
    s03_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s03_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s03_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s03_axi_rlast : out STD_LOGIC;
    s03_axi_rvalid : out STD_LOGIC;
    s03_axi_rready : in STD_LOGIC;
    s04_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s04_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s04_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s04_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s04_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s04_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s04_axi_awvalid : in STD_LOGIC;
    s04_axi_awlock : in STD_LOGIC;
    s04_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s04_axi_awready : out STD_LOGIC;
    s04_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s04_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s04_axi_wlast : in STD_LOGIC;
    s04_axi_wvalid : in STD_LOGIC;
    s04_axi_wready : out STD_LOGIC;
    s04_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s04_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s04_axi_bvalid : out STD_LOGIC;
    s04_axi_bready : in STD_LOGIC;
    s04_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s04_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s04_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s04_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s04_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s04_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s04_axi_arvalid : in STD_LOGIC;
    s04_axi_arlock : in STD_LOGIC;
    s04_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s04_axi_arready : out STD_LOGIC;
    s04_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s04_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s04_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s04_axi_rlast : out STD_LOGIC;
    s04_axi_rvalid : out STD_LOGIC;
    s04_axi_rready : in STD_LOGIC;
    s05_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s05_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s05_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s05_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s05_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s05_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s05_axi_awvalid : in STD_LOGIC;
    s05_axi_awlock : in STD_LOGIC;
    s05_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s05_axi_awready : out STD_LOGIC;
    s05_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s05_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s05_axi_wlast : in STD_LOGIC;
    s05_axi_wvalid : in STD_LOGIC;
    s05_axi_wready : out STD_LOGIC;
    s05_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s05_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s05_axi_bvalid : out STD_LOGIC;
    s05_axi_bready : in STD_LOGIC;
    s05_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s05_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s05_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s05_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s05_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s05_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s05_axi_arvalid : in STD_LOGIC;
    s05_axi_arlock : in STD_LOGIC;
    s05_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s05_axi_arready : out STD_LOGIC;
    s05_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s05_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s05_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s05_axi_rlast : out STD_LOGIC;
    s05_axi_rvalid : out STD_LOGIC;
    s05_axi_rready : in STD_LOGIC;
    s06_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s06_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s06_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s06_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s06_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s06_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s06_axi_awvalid : in STD_LOGIC;
    s06_axi_awlock : in STD_LOGIC;
    s06_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s06_axi_awready : out STD_LOGIC;
    s06_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s06_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s06_axi_wlast : in STD_LOGIC;
    s06_axi_wvalid : in STD_LOGIC;
    s06_axi_wready : out STD_LOGIC;
    s06_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s06_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s06_axi_bvalid : out STD_LOGIC;
    s06_axi_bready : in STD_LOGIC;
    s06_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s06_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s06_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s06_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s06_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s06_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s06_axi_arvalid : in STD_LOGIC;
    s06_axi_arlock : in STD_LOGIC;
    s06_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s06_axi_arready : out STD_LOGIC;
    s06_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s06_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s06_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s06_axi_rlast : out STD_LOGIC;
    s06_axi_rvalid : out STD_LOGIC;
    s06_axi_rready : in STD_LOGIC;
    s07_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s07_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s07_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s07_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s07_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s07_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s07_axi_awvalid : in STD_LOGIC;
    s07_axi_awlock : in STD_LOGIC;
    s07_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s07_axi_awready : out STD_LOGIC;
    s07_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s07_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s07_axi_wlast : in STD_LOGIC;
    s07_axi_wvalid : in STD_LOGIC;
    s07_axi_wready : out STD_LOGIC;
    s07_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s07_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s07_axi_bvalid : out STD_LOGIC;
    s07_axi_bready : in STD_LOGIC;
    s07_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s07_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s07_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s07_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s07_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s07_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s07_axi_arvalid : in STD_LOGIC;
    s07_axi_arlock : in STD_LOGIC;
    s07_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s07_axi_arready : out STD_LOGIC;
    s07_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s07_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s07_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s07_axi_rlast : out STD_LOGIC;
    s07_axi_rvalid : out STD_LOGIC;
    s07_axi_rready : in STD_LOGIC;
    s08_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s08_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s08_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s08_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s08_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s08_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s08_axi_awvalid : in STD_LOGIC;
    s08_axi_awlock : in STD_LOGIC;
    s08_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s08_axi_awready : out STD_LOGIC;
    s08_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s08_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s08_axi_wlast : in STD_LOGIC;
    s08_axi_wvalid : in STD_LOGIC;
    s08_axi_wready : out STD_LOGIC;
    s08_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s08_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s08_axi_bvalid : out STD_LOGIC;
    s08_axi_bready : in STD_LOGIC;
    s08_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s08_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s08_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s08_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s08_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s08_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s08_axi_arvalid : in STD_LOGIC;
    s08_axi_arlock : in STD_LOGIC;
    s08_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s08_axi_arready : out STD_LOGIC;
    s08_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s08_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s08_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s08_axi_rlast : out STD_LOGIC;
    s08_axi_rvalid : out STD_LOGIC;
    s08_axi_rready : in STD_LOGIC;
    s09_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s09_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s09_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s09_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s09_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s09_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s09_axi_awvalid : in STD_LOGIC;
    s09_axi_awlock : in STD_LOGIC;
    s09_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s09_axi_awready : out STD_LOGIC;
    s09_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s09_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s09_axi_wlast : in STD_LOGIC;
    s09_axi_wvalid : in STD_LOGIC;
    s09_axi_wready : out STD_LOGIC;
    s09_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s09_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s09_axi_bvalid : out STD_LOGIC;
    s09_axi_bready : in STD_LOGIC;
    s09_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s09_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s09_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s09_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s09_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s09_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s09_axi_arvalid : in STD_LOGIC;
    s09_axi_arlock : in STD_LOGIC;
    s09_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s09_axi_arready : out STD_LOGIC;
    s09_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s09_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s09_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s09_axi_rlast : out STD_LOGIC;
    s09_axi_rvalid : out STD_LOGIC;
    s09_axi_rready : in STD_LOGIC;
    s10_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s10_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s10_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s10_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s10_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s10_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s10_axi_awvalid : in STD_LOGIC;
    s10_axi_awlock : in STD_LOGIC;
    s10_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s10_axi_awready : out STD_LOGIC;
    s10_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s10_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s10_axi_wlast : in STD_LOGIC;
    s10_axi_wvalid : in STD_LOGIC;
    s10_axi_wready : out STD_LOGIC;
    s10_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s10_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s10_axi_bvalid : out STD_LOGIC;
    s10_axi_bready : in STD_LOGIC;
    s10_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s10_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s10_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s10_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s10_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s10_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s10_axi_arvalid : in STD_LOGIC;
    s10_axi_arlock : in STD_LOGIC;
    s10_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s10_axi_arready : out STD_LOGIC;
    s10_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s10_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s10_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s10_axi_rlast : out STD_LOGIC;
    s10_axi_rvalid : out STD_LOGIC;
    s10_axi_rready : in STD_LOGIC;
    s11_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s11_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s11_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s11_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s11_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s11_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s11_axi_awvalid : in STD_LOGIC;
    s11_axi_awlock : in STD_LOGIC;
    s11_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s11_axi_awready : out STD_LOGIC;
    s11_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s11_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s11_axi_wlast : in STD_LOGIC;
    s11_axi_wvalid : in STD_LOGIC;
    s11_axi_wready : out STD_LOGIC;
    s11_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s11_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s11_axi_bvalid : out STD_LOGIC;
    s11_axi_bready : in STD_LOGIC;
    s11_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s11_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s11_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s11_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s11_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s11_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s11_axi_arvalid : in STD_LOGIC;
    s11_axi_arlock : in STD_LOGIC;
    s11_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s11_axi_arready : out STD_LOGIC;
    s11_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s11_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s11_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s11_axi_rlast : out STD_LOGIC;
    s11_axi_rvalid : out STD_LOGIC;
    s11_axi_rready : in STD_LOGIC;
    s12_axi_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s12_axi_awaddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s12_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s12_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s12_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s12_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s12_axi_awvalid : in STD_LOGIC;
    s12_axi_awlock : in STD_LOGIC;
    s12_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s12_axi_awready : out STD_LOGIC;
    s12_axi_wdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s12_axi_wstrb : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s12_axi_wlast : in STD_LOGIC;
    s12_axi_wvalid : in STD_LOGIC;
    s12_axi_wready : out STD_LOGIC;
    s12_axi_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s12_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s12_axi_bvalid : out STD_LOGIC;
    s12_axi_bready : in STD_LOGIC;
    s12_axi_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s12_axi_araddr : in STD_LOGIC_VECTOR ( 63 downto 0 );
    s12_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s12_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s12_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s12_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s12_axi_arvalid : in STD_LOGIC;
    s12_axi_arlock : in STD_LOGIC;
    s12_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s12_axi_arready : out STD_LOGIC;
    s12_axi_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    s12_axi_rdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    s12_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s12_axi_rlast : out STD_LOGIC;
    s12_axi_rvalid : out STD_LOGIC;
    s12_axi_rready : in STD_LOGIC;
    s_axi_lite_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_lite_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_lite_awvalid : in STD_LOGIC;
    s_axi_lite_awready : out STD_LOGIC;
    s_axi_lite_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_lite_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_lite_wvalid : in STD_LOGIC;
    s_axi_lite_wready : out STD_LOGIC;
    s_axi_lite_bvalid : out STD_LOGIC;
    s_axi_lite_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_lite_bready : in STD_LOGIC;
    s_axi_lite_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_lite_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_lite_arvalid : in STD_LOGIC;
    s_axi_lite_arready : out STD_LOGIC;
    s_axi_lite_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_lite_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_lite_rvalid : out STD_LOGIC;
    s_axi_lite_rready : in STD_LOGIC;
    UART_RX : in STD_LOGIC_VECTOR ( 11 downto 0 );
    UART_TX : out STD_LOGIC_VECTOR ( 11 downto 0 )
  );

end design_1_bridge_top_v2_0_0;

architecture stub of design_1_bridge_top_v2_0_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "clk,rst,interupt_req,interupt_ack,LOGIC_VERSION[31:0],LOGIC_SUB_VERSION[31:0],s01_axi_awid[3:0],s01_axi_awaddr[63:0],s01_axi_awlen[7:0],s01_axi_awsize[2:0],s01_axi_awburst[1:0],s01_axi_awprot[2:0],s01_axi_awvalid,s01_axi_awlock,s01_axi_awcache[3:0],s01_axi_awready,s01_axi_wdata[63:0],s01_axi_wstrb[7:0],s01_axi_wlast,s01_axi_wvalid,s01_axi_wready,s01_axi_bid[3:0],s01_axi_bresp[1:0],s01_axi_bvalid,s01_axi_bready,s01_axi_arid[3:0],s01_axi_araddr[63:0],s01_axi_arlen[7:0],s01_axi_arsize[2:0],s01_axi_arburst[1:0],s01_axi_arprot[2:0],s01_axi_arvalid,s01_axi_arlock,s01_axi_arcache[3:0],s01_axi_arready,s01_axi_rid[3:0],s01_axi_rdata[63:0],s01_axi_rresp[1:0],s01_axi_rlast,s01_axi_rvalid,s01_axi_rready,s02_axi_awid[3:0],s02_axi_awaddr[63:0],s02_axi_awlen[7:0],s02_axi_awsize[2:0],s02_axi_awburst[1:0],s02_axi_awprot[2:0],s02_axi_awvalid,s02_axi_awlock,s02_axi_awcache[3:0],s02_axi_awready,s02_axi_wdata[63:0],s02_axi_wstrb[7:0],s02_axi_wlast,s02_axi_wvalid,s02_axi_wready,s02_axi_bid[3:0],s02_axi_bresp[1:0],s02_axi_bvalid,s02_axi_bready,s02_axi_arid[3:0],s02_axi_araddr[63:0],s02_axi_arlen[7:0],s02_axi_arsize[2:0],s02_axi_arburst[1:0],s02_axi_arprot[2:0],s02_axi_arvalid,s02_axi_arlock,s02_axi_arcache[3:0],s02_axi_arready,s02_axi_rid[3:0],s02_axi_rdata[63:0],s02_axi_rresp[1:0],s02_axi_rlast,s02_axi_rvalid,s02_axi_rready,s03_axi_awid[3:0],s03_axi_awaddr[63:0],s03_axi_awlen[7:0],s03_axi_awsize[2:0],s03_axi_awburst[1:0],s03_axi_awprot[2:0],s03_axi_awvalid,s03_axi_awlock,s03_axi_awcache[3:0],s03_axi_awready,s03_axi_wdata[63:0],s03_axi_wstrb[7:0],s03_axi_wlast,s03_axi_wvalid,s03_axi_wready,s03_axi_bid[3:0],s03_axi_bresp[1:0],s03_axi_bvalid,s03_axi_bready,s03_axi_arid[3:0],s03_axi_araddr[63:0],s03_axi_arlen[7:0],s03_axi_arsize[2:0],s03_axi_arburst[1:0],s03_axi_arprot[2:0],s03_axi_arvalid,s03_axi_arlock,s03_axi_arcache[3:0],s03_axi_arready,s03_axi_rid[3:0],s03_axi_rdata[63:0],s03_axi_rresp[1:0],s03_axi_rlast,s03_axi_rvalid,s03_axi_rready,s04_axi_awid[3:0],s04_axi_awaddr[63:0],s04_axi_awlen[7:0],s04_axi_awsize[2:0],s04_axi_awburst[1:0],s04_axi_awprot[2:0],s04_axi_awvalid,s04_axi_awlock,s04_axi_awcache[3:0],s04_axi_awready,s04_axi_wdata[63:0],s04_axi_wstrb[7:0],s04_axi_wlast,s04_axi_wvalid,s04_axi_wready,s04_axi_bid[3:0],s04_axi_bresp[1:0],s04_axi_bvalid,s04_axi_bready,s04_axi_arid[3:0],s04_axi_araddr[63:0],s04_axi_arlen[7:0],s04_axi_arsize[2:0],s04_axi_arburst[1:0],s04_axi_arprot[2:0],s04_axi_arvalid,s04_axi_arlock,s04_axi_arcache[3:0],s04_axi_arready,s04_axi_rid[3:0],s04_axi_rdata[63:0],s04_axi_rresp[1:0],s04_axi_rlast,s04_axi_rvalid,s04_axi_rready,s05_axi_awid[3:0],s05_axi_awaddr[63:0],s05_axi_awlen[7:0],s05_axi_awsize[2:0],s05_axi_awburst[1:0],s05_axi_awprot[2:0],s05_axi_awvalid,s05_axi_awlock,s05_axi_awcache[3:0],s05_axi_awready,s05_axi_wdata[63:0],s05_axi_wstrb[7:0],s05_axi_wlast,s05_axi_wvalid,s05_axi_wready,s05_axi_bid[3:0],s05_axi_bresp[1:0],s05_axi_bvalid,s05_axi_bready,s05_axi_arid[3:0],s05_axi_araddr[63:0],s05_axi_arlen[7:0],s05_axi_arsize[2:0],s05_axi_arburst[1:0],s05_axi_arprot[2:0],s05_axi_arvalid,s05_axi_arlock,s05_axi_arcache[3:0],s05_axi_arready,s05_axi_rid[3:0],s05_axi_rdata[63:0],s05_axi_rresp[1:0],s05_axi_rlast,s05_axi_rvalid,s05_axi_rready,s06_axi_awid[3:0],s06_axi_awaddr[63:0],s06_axi_awlen[7:0],s06_axi_awsize[2:0],s06_axi_awburst[1:0],s06_axi_awprot[2:0],s06_axi_awvalid,s06_axi_awlock,s06_axi_awcache[3:0],s06_axi_awready,s06_axi_wdata[63:0],s06_axi_wstrb[7:0],s06_axi_wlast,s06_axi_wvalid,s06_axi_wready,s06_axi_bid[3:0],s06_axi_bresp[1:0],s06_axi_bvalid,s06_axi_bready,s06_axi_arid[3:0],s06_axi_araddr[63:0],s06_axi_arlen[7:0],s06_axi_arsize[2:0],s06_axi_arburst[1:0],s06_axi_arprot[2:0],s06_axi_arvalid,s06_axi_arlock,s06_axi_arcache[3:0],s06_axi_arready,s06_axi_rid[3:0],s06_axi_rdata[63:0],s06_axi_rresp[1:0],s06_axi_rlast,s06_axi_rvalid,s06_axi_rready,s07_axi_awid[3:0],s07_axi_awaddr[63:0],s07_axi_awlen[7:0],s07_axi_awsize[2:0],s07_axi_awburst[1:0],s07_axi_awprot[2:0],s07_axi_awvalid,s07_axi_awlock,s07_axi_awcache[3:0],s07_axi_awready,s07_axi_wdata[63:0],s07_axi_wstrb[7:0],s07_axi_wlast,s07_axi_wvalid,s07_axi_wready,s07_axi_bid[3:0],s07_axi_bresp[1:0],s07_axi_bvalid,s07_axi_bready,s07_axi_arid[3:0],s07_axi_araddr[63:0],s07_axi_arlen[7:0],s07_axi_arsize[2:0],s07_axi_arburst[1:0],s07_axi_arprot[2:0],s07_axi_arvalid,s07_axi_arlock,s07_axi_arcache[3:0],s07_axi_arready,s07_axi_rid[3:0],s07_axi_rdata[63:0],s07_axi_rresp[1:0],s07_axi_rlast,s07_axi_rvalid,s07_axi_rready,s08_axi_awid[3:0],s08_axi_awaddr[63:0],s08_axi_awlen[7:0],s08_axi_awsize[2:0],s08_axi_awburst[1:0],s08_axi_awprot[2:0],s08_axi_awvalid,s08_axi_awlock,s08_axi_awcache[3:0],s08_axi_awready,s08_axi_wdata[63:0],s08_axi_wstrb[7:0],s08_axi_wlast,s08_axi_wvalid,s08_axi_wready,s08_axi_bid[3:0],s08_axi_bresp[1:0],s08_axi_bvalid,s08_axi_bready,s08_axi_arid[3:0],s08_axi_araddr[63:0],s08_axi_arlen[7:0],s08_axi_arsize[2:0],s08_axi_arburst[1:0],s08_axi_arprot[2:0],s08_axi_arvalid,s08_axi_arlock,s08_axi_arcache[3:0],s08_axi_arready,s08_axi_rid[3:0],s08_axi_rdata[63:0],s08_axi_rresp[1:0],s08_axi_rlast,s08_axi_rvalid,s08_axi_rready,s09_axi_awid[3:0],s09_axi_awaddr[63:0],s09_axi_awlen[7:0],s09_axi_awsize[2:0],s09_axi_awburst[1:0],s09_axi_awprot[2:0],s09_axi_awvalid,s09_axi_awlock,s09_axi_awcache[3:0],s09_axi_awready,s09_axi_wdata[63:0],s09_axi_wstrb[7:0],s09_axi_wlast,s09_axi_wvalid,s09_axi_wready,s09_axi_bid[3:0],s09_axi_bresp[1:0],s09_axi_bvalid,s09_axi_bready,s09_axi_arid[3:0],s09_axi_araddr[63:0],s09_axi_arlen[7:0],s09_axi_arsize[2:0],s09_axi_arburst[1:0],s09_axi_arprot[2:0],s09_axi_arvalid,s09_axi_arlock,s09_axi_arcache[3:0],s09_axi_arready,s09_axi_rid[3:0],s09_axi_rdata[63:0],s09_axi_rresp[1:0],s09_axi_rlast,s09_axi_rvalid,s09_axi_rready,s10_axi_awid[3:0],s10_axi_awaddr[63:0],s10_axi_awlen[7:0],s10_axi_awsize[2:0],s10_axi_awburst[1:0],s10_axi_awprot[2:0],s10_axi_awvalid,s10_axi_awlock,s10_axi_awcache[3:0],s10_axi_awready,s10_axi_wdata[63:0],s10_axi_wstrb[7:0],s10_axi_wlast,s10_axi_wvalid,s10_axi_wready,s10_axi_bid[3:0],s10_axi_bresp[1:0],s10_axi_bvalid,s10_axi_bready,s10_axi_arid[3:0],s10_axi_araddr[63:0],s10_axi_arlen[7:0],s10_axi_arsize[2:0],s10_axi_arburst[1:0],s10_axi_arprot[2:0],s10_axi_arvalid,s10_axi_arlock,s10_axi_arcache[3:0],s10_axi_arready,s10_axi_rid[3:0],s10_axi_rdata[63:0],s10_axi_rresp[1:0],s10_axi_rlast,s10_axi_rvalid,s10_axi_rready,s11_axi_awid[3:0],s11_axi_awaddr[63:0],s11_axi_awlen[7:0],s11_axi_awsize[2:0],s11_axi_awburst[1:0],s11_axi_awprot[2:0],s11_axi_awvalid,s11_axi_awlock,s11_axi_awcache[3:0],s11_axi_awready,s11_axi_wdata[63:0],s11_axi_wstrb[7:0],s11_axi_wlast,s11_axi_wvalid,s11_axi_wready,s11_axi_bid[3:0],s11_axi_bresp[1:0],s11_axi_bvalid,s11_axi_bready,s11_axi_arid[3:0],s11_axi_araddr[63:0],s11_axi_arlen[7:0],s11_axi_arsize[2:0],s11_axi_arburst[1:0],s11_axi_arprot[2:0],s11_axi_arvalid,s11_axi_arlock,s11_axi_arcache[3:0],s11_axi_arready,s11_axi_rid[3:0],s11_axi_rdata[63:0],s11_axi_rresp[1:0],s11_axi_rlast,s11_axi_rvalid,s11_axi_rready,s12_axi_awid[3:0],s12_axi_awaddr[63:0],s12_axi_awlen[7:0],s12_axi_awsize[2:0],s12_axi_awburst[1:0],s12_axi_awprot[2:0],s12_axi_awvalid,s12_axi_awlock,s12_axi_awcache[3:0],s12_axi_awready,s12_axi_wdata[63:0],s12_axi_wstrb[7:0],s12_axi_wlast,s12_axi_wvalid,s12_axi_wready,s12_axi_bid[3:0],s12_axi_bresp[1:0],s12_axi_bvalid,s12_axi_bready,s12_axi_arid[3:0],s12_axi_araddr[63:0],s12_axi_arlen[7:0],s12_axi_arsize[2:0],s12_axi_arburst[1:0],s12_axi_arprot[2:0],s12_axi_arvalid,s12_axi_arlock,s12_axi_arcache[3:0],s12_axi_arready,s12_axi_rid[3:0],s12_axi_rdata[63:0],s12_axi_rresp[1:0],s12_axi_rlast,s12_axi_rvalid,s12_axi_rready,s_axi_lite_awaddr[31:0],s_axi_lite_awprot[2:0],s_axi_lite_awvalid,s_axi_lite_awready,s_axi_lite_wdata[31:0],s_axi_lite_wstrb[3:0],s_axi_lite_wvalid,s_axi_lite_wready,s_axi_lite_bvalid,s_axi_lite_bresp[1:0],s_axi_lite_bready,s_axi_lite_araddr[31:0],s_axi_lite_arprot[2:0],s_axi_lite_arvalid,s_axi_lite_arready,s_axi_lite_rdata[31:0],s_axi_lite_rresp[1:0],s_axi_lite_rvalid,s_axi_lite_rready,UART_RX[11:0],UART_TX[11:0]";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "bridge_top_v2,Vivado 2022.2";
begin
end;
